[package]
name = "raytracing_diorama"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
raylib = "5.5.1"
rayon = "1.11"
num_cpus = "1.16"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
